databases:
  - name: rails_backend
    databaseName: rails_backend
    user: rails_backend
    plan: free

services:
  - type: web
    name: rails_backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rails_backend
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction